# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

def fibonacci_generator(maximum):
    """a generator for Fibonacci numbers up till 'maximum', 
    goes to next number in series on each call"""
    a, b = 1, 2
    while a < maximum:
        yield a
        a, b = b, a+b
    
print sum(i for i in fibonacci_generator(4000000) if not i%2)

# 4613732
#
# real	0m0.048s
# user	0m0.030s
# sys	0m0.010s

